version: '3.7'
services:
    
  
  myapp-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: sri-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: srischema
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - sri-web-application-network  
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  sri-web-application-network: